[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "curl -fsSL https://get.pnpm.io/install.sh | sh -",
  "export PNPM_HOME=$HOME/.local/share/pnpm",
  "export PATH=$PNPM_HOME:$PATH",
  "ln -sf $PNPM_HOME/pnpm /usr/local/bin/pnpm",
  "pnpm install --no-frozen-lockfile"
]

[phases.build]
cmds = [
  "pnpm prisma generate",
  "pnpm run build"
]

[deploy]
startCommand = "npx prisma migrate deploy && node dist/index.js"